# Generated by Django 4.2.8 on 2023-12-25 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Catering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=100)),


            ],
        ),
        migrations.CreateModel(
            name="Decoration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=200)),


            ],
        ),
        migrations.CreateModel(
            name="Photoshoot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.ImageField(upload_to="pic")),
                ("name", models.CharField(max_length=50)),
                ("desc", models.CharField(max_length=100)),


            ],
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cus_name", models.CharField(max_length=55)),
                ("cus_ph", models.CharField(max_length=10)),
                ("booking_date", models.DateField()),
                ("booked_on", models.DateField(auto_now=True)),
                (
                    "catering",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventapp.catering",
                    ),
                ),
                (
                    "decoration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventapp.decoration",
                    ),
                ),
                (
                    "photoshoot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eventapp.photoshoot",
                    ),
                ),
            ],
        ),
    ]
