# Generated by Django 4.2.8 on 2024-01-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0003_alter_catering_desc"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="total_amount",
            field=models.IntegerField(default=0),
        ),
    ]
