# Generated by Django 4.2.8 on 2024-01-06 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eventapp", "0004_booking_total_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="total_amount",
        ),
    ]
